/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 Labor.glb --transform --shadows --keepnames
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Labor(props) {
  const { nodes, materials } = useGLTF('/model/Labor-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Room" castShadow receiveShadow geometry={nodes.Room.geometry} material={materials.Plaster} position={[4.3, 1, 18.8]} />
    </group>
  )
}

useGLTF.preload('/model/Labor-transformed.glb')
