/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 Labor.glb --transform --shadows --keepnames
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import { RigidBody } from '@react-three/rapier';

export function Labor(props) {
  const { nodes, materials } = useGLTF('/model/Labor-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <RigidBody colliders='trimesh' type='fixed'>
        <mesh name="Room" castShadow receiveShadow geometry={nodes.Room.geometry} material={materials['plaster white']} />
      </RigidBody>
    </group>
  );
}

useGLTF.preload('/model/Labor-transformed.glb');
